version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: America/Chicago
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
